Repository DanielTeelOU/Golf-Player-Time-Manager, pull requests merged in 2020-03, with the labels that each got.

#57 final styling tweaks and demo build
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/course-map/course-map.component.html
  GPTM Cloud App/admin-app/src/app/course-map/course-map.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/course-overview.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/course-overview.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole01/hole01.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole02/hole02.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole03/hole03.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole04/hole04.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole05/hole05.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole06/hole06.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole07/hole07.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole08/hole08.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole09/hole09.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole10/hole10.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole11/hole11.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole12/hole12.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole13/hole13.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole14/hole14.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole15/hole15.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole16/hole16.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole17/hole17.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole18/hole18.component.css
Labels: Website

#58 sprint 4 admin qa
  Documentation/QA Testing/Admin Website QA.docx
Labels: documentation

#62 Player Overview ui mockup and user story
  Documentation/UI Mockups/Admin Site Player Overview.pdf
  Documentation/User Stories/Admin Site Player Overview User Story.docx
Labels: documentation

#65 All documents from sprint 4
  Documentation/GPTM Documentation.docx
  Documentation/UI Mockups/UIUXdesign_assistance_NEW.png
  Documentation/UI Mockups/UIUXdesign_assistance_OLD.PNG
  Documentation/User Stories/Assistance User Stories.docx
Labels: documentation

#68 Feature/hole marker player overview
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/functions/src/index.ts
  GPTM Cloud App/admin-app/package-lock.json
  GPTM Cloud App/admin-app/package.json
  GPTM Cloud App/admin-app/src/app/app.module.ts
  GPTM Cloud App/admin-app/src/app/course-map/course-map.component.html
  GPTM Cloud App/admin-app/src/app/course-map/course-map.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole01/hole01.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole01/hole01.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole02/hole02.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole02/hole02.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole03/hole03.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole03/hole03.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole04/hole04.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole04/hole04.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole05/hole05.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole05/hole05.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole06/hole06.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole06/hole06.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole07/hole07.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole07/hole07.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole08/hole08.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole08/hole08.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole09/hole09.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole09/hole09.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole10/hole10.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole10/hole10.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole11/hole11.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole11/hole11.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole12/hole12.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole12/hole12.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole13/hole13.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole13/hole13.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole14/hole14.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole14/hole14.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole15/hole15.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole15/hole15.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole16/hole16.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole16/hole16.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole17/hole17.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole17/hole17.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole18/hole18.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole18/hole18.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/player-overview.component.css
  GPTM Cloud App/admin-app/src/app/player-overview/player-overview.component.html
  GPTM Cloud App/admin-app/src/app/player-overview/player-overview.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.css
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.html
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.spec.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/requests-table/requests-table.component.css
  GPTM Cloud App/admin-app/src/app/player-overview/tables/requests-table/requests-table.component.html
  GPTM Cloud App/admin-app/src/app/player-overview/tables/requests-table/requests-table.component.spec.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/requests-table/requests-table.component.ts
  GPTM Cloud App/admin-app/src/app/register/register.component.css
  GPTM Cloud App/admin-app/src/app/register/register.component.html
  GPTM Cloud App/admin-app/src/app/register/register.component.ts
  GPTM Cloud App/admin-app/src/app/support/support.component.css
  GPTM Cloud App/admin-app/src/app/support/support.component.html
Labels: Website

#71 QA testing and css tweaks
  Documentation/QA Testing/Admin Website QA.docx
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.css
  GPTM Cloud App/admin-app/src/app/player-overview/tables/requests-table/requests-table.component.css
Labels: Website, documentation

#72 Feature/support page
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/support/support.component.html
Labels: Website

#74 Documentation Updates
  Documentation/GPTM Documentation.docx
  Documentation/Mobile App Interface Design Guide.docx
Labels: documentation

#75 Feature/predict wait times
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/package-lock.json
  GPTM Cloud App/admin-app/package.json
  GPTM Cloud App/admin-app/src/app/app.module.ts
  GPTM Cloud App/admin-app/src/app/course-overview/course-overview-accordion.txt
  GPTM Cloud App/admin-app/src/app/course-overview/course-overview.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/course-overview.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/course-overview.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/eli-demo.txt
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/wait-time/wait-time.component.css
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/wait-time/wait-time.component.html
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/wait-time/wait-time.component.spec.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/wait-time/wait-time.component.ts
  GPTM Cloud App/admin-app/src/app/items/item-detail/item-detail.component.css
  GPTM Cloud App/admin-app/src/app/items/item-detail/item-detail.component.html
  GPTM Cloud App/admin-app/src/app/items/item-detail/item-detail.component.ts
  GPTM Cloud App/admin-app/src/app/items/item-form/item-form.component.css
  GPTM Cloud App/admin-app/src/app/items/item-form/item-form.component.html
  GPTM Cloud App/admin-app/src/app/items/item-form/item-form.component.spec.ts
  GPTM Cloud App/admin-app/src/app/items/item-form/item-form.component.ts
  GPTM Cloud App/admin-app/src/app/items/items-list/items-list.component.css
  GPTM Cloud App/admin-app/src/app/items/items-list/items-list.component.html
  GPTM Cloud App/admin-app/src/app/items/items-list/items-list.component.spec.ts
  GPTM Cloud App/admin-app/src/app/items/items-list/items-list.component.ts
  GPTM Cloud App/admin-app/src/app/items/shared/item.service.spec.ts
  GPTM Cloud App/admin-app/src/app/items/shared/item.service.ts
  GPTM Cloud App/admin-app/src/app/items/shared/item.spec.ts
  GPTM Cloud App/admin-app/src/app/items/shared/item.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.html
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.ts
  GPTM Cloud App/admin-app/src/app/register/register.component.ts
  GPTM Cloud App/admin-app/src/app/support/support.component.html
  GPTM Cloud App/admin-app/src/app/user/user.component.ts
Labels: Website

#77 comments, css fix for larger screen aspect ratios
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/app-routing.module.ts
  GPTM Cloud App/admin-app/src/app/app.component.ts
  GPTM Cloud App/admin-app/src/app/app.module.ts
  GPTM Cloud App/admin-app/src/app/authentication/auth.guard.ts
  GPTM Cloud App/admin-app/src/app/authentication/user.model.ts
  GPTM Cloud App/admin-app/src/app/course-map/course-map.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/course-overview.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole01/hole01.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/wait-time/wait-time.component.css
  GPTM Cloud App/admin-app/src/app/home/home.component.css
  GPTM Cloud App/admin-app/src/app/login/login.component.css
  GPTM Cloud App/admin-app/src/app/login/login.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/player-overview.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/requests-table/requests-table.component.ts
  GPTM Cloud App/admin-app/src/app/register/register.component.css
  GPTM Cloud App/admin-app/src/app/register/register.component.ts
  GPTM Cloud App/admin-app/src/app/services/auth.service.ts
  GPTM Cloud App/admin-app/src/app/support/support.component.html
  GPTM Cloud App/admin-app/src/app/support/support.component.ts
  GPTM Cloud App/admin-app/src/app/user/user.component.ts
  GPTM Cloud App/admin-app/src/app/user/user.resolver.ts
Labels: Website

#81 password reset functionality
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/app.module.ts
  GPTM Cloud App/admin-app/src/app/login/login.component.html
  GPTM Cloud App/admin-app/src/app/login/login.component.ts
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.css
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.html
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.spec.ts
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.ts
  GPTM Cloud App/admin-app/src/app/register/register.component.ts
Labels: Website

#82 switched to loading bar, added null check
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.html
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.ts
Labels: Website, bugfix

#84 production mode enabled, version set to 1
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/package.json
  GPTM Cloud App/admin-app/src/app/login/login.component.html
  GPTM Cloud App/admin-app/src/environments/environment.ts
Labels: Website

#86 tables update significantly faster
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/wait-time/wait-time.component.ts
  GPTM Cloud App/admin-app/src/app/user/user.component.ts
Labels: Website

#88 Bugfix/init par and yds to zero
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/register/register.component.ts
Labels: Website

#90 Finish/website console warnings
  .DS_Store
  Documentation/.DS_Store
  Documentation/Presentations/Sprint Presentation 5.pptx
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/app.component.ts
  GPTM Cloud App/admin-app/src/app/course-map/course-map.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/course-overview.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole01/hole01.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole02/hole02.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole03/hole03.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole04/hole04.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole05/hole05.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole06/hole06.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole07/hole07.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole08/hole08.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole09/hole09.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole10/hole10.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole11/hole11.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole12/hole12.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole13/hole13.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole14/hole14.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole15/hole15.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole16/hole16.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole17/hole17.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole18/hole18.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/wait-time/wait-time.component.ts
  GPTM Cloud App/admin-app/src/app/login/login.component.ts
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.html
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/player-overview.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/requests-table/requests-table.component.ts
  GPTM Cloud App/admin-app/src/app/register/register.component.ts
  GPTM Cloud App/admin-app/src/app/services/auth.service.ts
  GPTM Cloud App/admin-app/src/app/services/user.service.ts
  GPTM Cloud App/admin-app/src/app/user/user.component.ts
  GPTM Cloud App/admin-app/src/environments/environment.ts
Labels: Website, bugfix

#93 Documentation Update for Sprint 6
  Documentation/GPTM Documentation.docx
  Documentation/Posters/gptm_mobile_poster.png
  Documentation/Posters/gptm_website_poster.png
Labels: documentation

#94 bugfix/user verification, edit cancel, map pop up close console error
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/functions/src/index.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole01/hole01.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole02/hole02.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole03/hole03.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole04/hole04.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole05/hole05.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole06/hole06.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole07/hole07.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole08/hole08.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole09/hole09.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole10/hole10.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole11/hole11.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole12/hole12.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole13/hole13.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole14/hole14.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole15/hole15.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole16/hole16.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole17/hole17.component.ts
  GPTM Cloud App/admin-app/src/app/course-overview/hole-info/hole18/hole18.component.ts
  GPTM Cloud App/admin-app/src/app/login/login.component.html
  GPTM Cloud App/admin-app/src/app/login/login.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/tables/active-player-table/active-player-table.component.ts
  GPTM Cloud App/admin-app/src/app/register/register.component.ts
Labels: Website, bugfix

#95 change account password implemented
  GPTM Cloud App/admin-app/.firebase/hosting.ZGlzdC9hZG1pbi1hcHA.cache
  GPTM Cloud App/admin-app/src/app/home/home.component.html
  GPTM Cloud App/admin-app/src/app/login/login.component.ts
  GPTM Cloud App/admin-app/src/app/login/password-reset/password-reset.component.ts
  GPTM Cloud App/admin-app/src/app/player-overview/player-overview.component.html
  GPTM Cloud App/admin-app/src/app/support/support.component.css
  GPTM Cloud App/admin-app/src/app/support/support.component.html
  GPTM Cloud App/admin-app/src/app/support/support.component.ts
Labels: Website
